language: php

php:
    - 5.4

before_script:
    - php -S localhost:8080 -t web/ 2> /dev/null &
    - cp behat.yml{-dist,}
    - curl http://getcomposer.org/installer | php
    - php composer.phar install --dev --prefer-source

script:
    - ./bin/behat -fprogress
